package jdbc;
// Generated 07-feb-2019 17:27:07 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * Multas generated by hbm2java
 */
public class Multas implements java.io.Serializable {

	private int codmulta;
	private Vehiculo vehiculo;
	private Date fecha;
	private String lugar;
	private int tipo;
	private double sancion;

	public Multas() {
	}

	public Multas(int codmulta, Vehiculo vehiculo, Date fecha, String lugar, int tipo, double sancion) {
		this.codmulta = codmulta;
		this.vehiculo = vehiculo;
		this.fecha = fecha;
		this.lugar = lugar;
		this.tipo = tipo;
		this.sancion = sancion;
	}

	public int getCodmulta() {
		return this.codmulta;
	}

	public void setCodmulta(int codmulta) {
		this.codmulta = codmulta;
	}

	public Vehiculo getVehiculo() {
		return this.vehiculo;
	}

	public void setVehiculo(Vehiculo vehiculo) {
		this.vehiculo = vehiculo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	public double getSancion() {
		return this.sancion;
	}

	public void setSancion(double sancion) {
		this.sancion = sancion;
	}

}
