

package jdbc;
// Generated 07-feb-2019 17:27:07 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo implements java.io.Serializable {

	private String matricula;
	private Conductor conductor;
	private String marca;
	private String modelo;
	private int cv;
	private Set<Multas> multases = new HashSet<Multas>(0);

	public Vehiculo() {
	}

	public Vehiculo(String matricula, Conductor conductor, String marca, String modelo, int cv) {
		this.matricula = matricula;
		this.conductor = conductor;
		this.marca = marca;
		this.modelo = modelo;
		this.cv = cv;
	}

	public Vehiculo(String matricula, Conductor conductor, String marca, String modelo, int cv, Set<Multas> multases) {
		this.matricula = matricula;
		this.conductor = conductor;
		this.marca = marca;
		this.modelo = modelo;
		this.cv = cv;
		this.multases = multases;
	}

	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	public Conductor getConductor() {
		return this.conductor;
	}

	public void setConductor(Conductor conductor) {
		this.conductor = conductor;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public int getCv() {
		return this.cv;
	}

	public void setCv(int cv) {
		this.cv = cv;
	}

	public Set<Multas> getMultases() {
		return this.multases;
	}

	public void setMultases(Set<Multas> multases) {
		this.multases = multases;
	}

	@Override
	public String toString() {
		return "Vehiculo [matricula=" + matricula + ", conductor=" + conductor + ", marca=" + marca + ", modelo="
				+ modelo + ", cv=" + cv +  "]";
	}
	
	

}
